package com.devsuperior.dslist.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "tb_game_list") // maps the class to the "tb_game_list" table in the database
public class GameList {

    @Id 
    // defines the field "id" as the primary key of the entity
    // The primary key is used to uniquely identify each game list in the database
    // The value of "id" will be generated automatically by the database
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY) 
    // specifies that the primary key will be generated by the database
    // The strategy "IDENTITY" means that the database will automatically generate a unique value for   
    private Long id;
    
    private String name;


    public GameList() {
    }

    public GameList(Long id, String name) {
        this.id = id;
        this.name = name;
    }    

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GameList other = (GameList) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }

}
